export enum ROW_STATUS {
  AG_VALIDACAO = 'AG VALIDAÇÃO',
  ANALISE_CONCLUIDA = 'ANÁLISE CONCLUÍDA', 
  EM_ANALISE = 'EM ANÁLISE', 
  NAO_LOCALIZADO = 'NÃO LOCALIZADO', 
  SEM_ACESSO_BANCARIO = 'SEM ACESSO BANCÁRIO',
  VALIDADO = 'VALIDADO',
}