export enum ATTACHMENT_TYPE {
  ALVARA_JUDICIAL = 'ALVARÁ JUDICIAL',
  BOLETO_DEPOSITO = 'BOLETO DE DEPÓSITO',
  COMPROVANTE_PAGAMENTO = 'COMPROVANTE DE PAGAMENTO',
  EXTRATO_BANCARIO = 'EXTRATO BANCÁRIO',
  OUTROS = 'OUTROS',
}